export const API_CODE = {
  SUCCESS: {
    LOGIN: 'LOGIN_SUCCESS',
    REGISTER: 'REGISTER_SUCCESS',
    REFRESH: 'REFRESH_SUCCESS',
    LOGOUT: 'LOGOUT_SUCCESS',
    WITHDRAW: 'WITHDRAW_SUCCESS',
    FETCH_USER: 'FETCH_USER_SUCCESS',
    CONNECTION_OK: 'CONNECTION_OK',
    FIND_ID: 'FIND_ID_SUCCESS',
    RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST_SUCCESS',
    RESET_PASSWORD_VERIFY: 'RESET_PASSWORD_VERIFY_SUCCESS',
    RESET_PASSWORD: 'RESET_PASSWORD_SUCCESS',
  },
  ERROR: {
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    USER_NOT_MATCH: 'USER_NOT_MATCH',
    INVALID_CODE: 'INVALID_CODE',
    EXPIRED_CODE: 'EXPIRED_CODE',
  },
} as const;

export type ApiCodeType = typeof API_CODE;
