export const API_CODE = {
  SUCCESS: {
    LOGIN: 'LOGIN_SUCCESS',
    REGISTER: 'REGISTER_SUCCESS',
    REFRESH: 'REFRESH_SUCCESS',
    LOGOUT: 'LOGOUT_SUCCESS',
    WITHDRAW: 'WITHDRAW_SUCCESS',
    FETCH_USER: 'FETCH_USER_SUCCESS',
    CONNECTION_OK: 'CONNECTION_OK',
  },
  ERROR: {
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    UNAUTHORIZED: 'UNAUTHORIZED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
  },
} as const;

export type ApiCodeType = typeof API_CODE;
